// <auto-generated />
namespace kamGuro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class bla : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bla));
        
        string IMigrationMetadata.Id
        {
            get { return "201409020200370_bla"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
